spring:
  application:
    name: gateway-api
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: token_validation
          uri: http://localhost:8083 # URL do Serviço de Autenticação
          predicates:
            - Path=/api/v1/auth/validate-token
          filters:
            - AddRequestHeader=Authorization, '{request.headers.Authorization}' # Adiciona o token do cabeçalho

        - id: autenticacao_service
          uri: http://localhost:8083 # URL do Serviço de Autenticação
          predicates:
            - Path=/api/v1/auth/**

        - id: lancamentos_service
          uri: http://localhost:8084 # URL do Serviço de Lançamentos
          predicates:
            - Path=/api/daily-balance/**
            - Path=/api/transaction/**
          filters:
            - StripPrefix=1

        - id: consolidacao_service
          uri: http://localhost:8085 # URL do Serviço de Consolidação
          predicates:
            - Path=/consolidacao/**

server:
  port: 8082
logging:
  level:
    org.springframework: DEBUG